// Roman/Vue.js/src/components/Figures/Square/SquareComponent.vue
<template>
  <div class="container row">
    <div class="col-md-12 mb-12">

      <TitleMessage :typeFigures='APP.types.square'></TitleMessage>

      <div class="row form-content">

        <div class='col-md-6 mb-6'>
          <b-form @submit="addSquare" class="form-row">
          <label for='square' class="text-left">Side length:</label>
          <b-form-input 
            id='square' 
            v-model.number='square'
            type='number'
            placeholder='10' 
            :min='minSquare' 
            :max='maxSquare' 
            step='0.1'   
            :state="squareState"
          ></b-form-input>
          <b-form-invalid-feedback id="input-live-feedback" class="text-left">
            Plese enter valid square
          </b-form-invalid-feedback>

          <b-button 
            type="submit"
            class="add-square-button"
            :variant='squareState ? "success": "danger"' 
            :disabled='!squareState || responseIsSuccess'
          >
            Add new {{ APP.types.square }}
            <ButtonSpinner v-if="responseIsSuccess"></ButtonSpinner>
          </b-button>

        </b-form>
      </div>
        
        <div class="col-md-6 mb-6 text-center">
          <FiguresInformation formula='S=a²' imageName='square.jpg'></FiguresInformation>
        </div>
        
      </div>
      
    </div>
  </div>
</template>

<script>
import TitleMessage from '@/components/Figures/TitleMessage'
import FiguresInformation from '@/components/Figures/FiguresInformation'
import ButtonSpinner from '@/components/ButtonSpinner'
import { APP } from '@/application-constants'

export default {
  name: 'Square',
  components: {
    TitleMessage,
    FiguresInformation,
    ButtonSpinner
  },
  props: ['responseIsSuccess'],
  data() {
    return {
      square: 10,
      minSquare: 0,
      maxSquare: 10000,
      APP
    }
  },
  computed: {
    squareState() {
      if (this.square > this.minSquare && this.square <= this.maxSquare) {
        return true;
      }
      return false
    }
  },
   methods: {

    getSquareArea() {
      const area = Math.pow(Number(this.square),2);
      return Math.round(area * 10000)/10000;
    },

    addSquare(evt) {
      evt.preventDefault();
      const area = this.getSquareArea();
      const data = {
        length: this.square
      }
      this.$emit('addFigures', APP.types.square, area, data);
    },
    
  }
}
</script>

<style scope>
  .form-content{
      margin: 25px;
  }
  .add-square-button{
    margin-top: 15px;
  }
</style>

// Roman/React/src/components/Square/Square.jsx
import React, {Component} from 'react';

import {Button, Form} from 'react-bootstrap';

import './Square.css';
import squareImg from '../../images/square.jpg';
import APP from '../../App-constants';


class Square extends Component{

  MINLENGTH = 0;
  MAXLENGTH = 1000;
  ACCURACY = 1000;
  INITIALLENGTH = 10; 
  STEP = 0.001;

  constructor(props) {
    super(props);
    this.state = {
      length: this.INITIALLENGTH,
      lengthValid: true,
    };

    this.handleChange = this.handleChange.bind(this);
    this.addSquare = this.addSquare.bind(this);
  }

  handleChange(event) {
    this.setState({length: event.target.value});
    if(event.target.value > this.MINLENGTH && event.target.value < this.MAXLENGTH){
      this.setState({lengthValid: true});
    }
    else this.setState({lengthValid: false});
  }

  getSquareArea() {
    const area = Math.pow(this.state.length,2)
    return Math.round(area * this.ACCURACY)/this.ACCURACY;
  }

  addSquare(event) {
    const area = this.getSquareArea();
    this.props.addFigures(APP.types.square, area, event);
  }

  render(){
    const {lengthValid, length} = this.state;

    return(
      <div className="container row">
        <div className="col-md-12 mb-12">

          <h3 className="text-center">Calculation of the area of a {APP.types.square}</h3>
          <hr />

          <div className="row form-content">

            <Form className='col-md-6 mb-6'>
              <Form.Group controlId="formLength">
                <Form.Label>Side length:</Form.Label>
                <Form.Control 
                  className={lengthValid?'is-valid':'is-invalid'}
                  type="number" 
                  step={this.STEP}
                  name="length" 
                  placeholder={this.INITIALLENGTH} 
                  min={this.MINLENGTH} 
                  max={this.MAXLENGTH} 
                  value={length} 
                  onChange={this.handleChange} 
                  required 
                />
                {
                  !lengthValid && <div className='alert alert-danger'>
                    Incorrect length
                  </div>
                }
              </Form.Group>
              <Button variant="success" type="submit" disabled={!lengthValid || this.props.responseIsSuccess} onClick={ (event) => this.addSquare(event) }>
                Add a new {APP.types.square}
                {
                  this.props.responseIsSuccess &&
                  <span className="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                }
              </Button>
            </Form>


            <div className="col-md-6 mb-6 text-center">
              <h4>
                Formula: 
                <code> S=a²</code>
              </h4>    
              <img src={squareImg} alt={APP.types.square} height="100"/> 
            </div>

          </div>
          
        </div>
      </div>
    );
  }
}

export default Square;
