// Roman/Angular/src/app/figures/figures.component.ts
import { Component } from '@angular/core';

import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { Figure } from '../models/figure'
import { FigureService } from '../services/figure.service';

@Component({
  selector: 'app-figures',
  templateUrl: './figures.component.html',
  styleUrls: ['./figures.component.css'],
})

export class FiguresComponent {
  
  public figures: Figure[];
  private figuresId: number;
  public showSpinner: boolean = true;
  public showDeleteSpinner: boolean = false;
  public showAlertMessage: boolean = false;
  public alertMessage: string;

  public page: number = 1;
  public pageSize: number = 5;
  public maxSize: number = 5;
  public collectionSize: number;

  constructor (
    private figureService: FigureService,
    private modalService: NgbModal, 
  ) {}

  open(content, id) {
    this.modalService.open(content);
    this.figuresId = id;
  }

  ngOnInit() {
    this.getFigures();
  }
  
  private getFigures(): void {
    this.figureService.getFigures()
      .subscribe(figures => {
        this.figures = figures.sort((first,second) => first.area-second.area);
        this.showSpinner = false;
        this.collectionSize = this.figures.length;
      });
  }
  
  public deleteFigures(): void {
    const id = this.figuresId;
    console.log(id);
    this.showDeleteSpinner = true;

    this.figureService.deleteFigure(id)
      .subscribe( response => {
        if(response.success){
          const index = this.figures.findIndex(figure => figure.id === id);

          this.figures.splice(index,1);
          
          this.showDeleteSpinner = false;
          this.modalService.dismissAll();

          this.alertMessage = `${id}`;
          this.showAlertMessage = true;
        }
      });
    
    

  }

}
<div *ngIf='showSpinner' class="d-flex justify-content-center align-items-center spinner">
  <div class="spinner-border text-primary" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<ngb-alert *ngIf='showAlertMessage' type='info' (close)="showAlertMessage = false" class="container alertDeleteSuccess text-center">
  Figures #{{ alertMessage }} successfully deleted
</ngb-alert>
  
<div *ngIf='!showSpinner' class="container text-center table-responsive list-figures">
  <table class="table table-bordered table-hover table-striped">
    <caption>List added figures</caption>

    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Type figures</th>
        <th scope="col">Area</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <tr *ngFor="let figure of figures | slice: (page-1) * pageSize : (page-1) * pageSize + pageSize">
        <th scope="row">{{ figure.id }}</th>
        <td> {{ figure.type }} </td>
        <td> {{ figure.area | number }} </td>
        <td>
          <!-- <button type="button" class="btn btn-outline-danger btn-sm" title="delete figure" (click)='deleteFigures(figure.id)' [disabled]='showDeleteSpinner'>
            Delete
            <span *ngIf='showDeleteSpinner' class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
          </button> -->

          <!-- <app-modal-del [id]="figure.id"></app-modal-del> -->
          <button class="btn btn-sm btn-outline-danger" (click)="open(content, figure.id)">Delete</button>
        </td>
      </tr>
    </tbody>

  </table>

  <div *ngIf='collectionSize > maxSize' class="container d-flex justify-content-center">
    <ngb-pagination
      [(page)]="page"
      [pageSize]="pageSize"
      [maxSize]="maxSize" 
      [rotate]="true" 
      [boundaryLinks]="true"
      [collectionSize]="collectionSize">
    </ngb-pagination>
  </div>

</div>


<ng-template #content let-c="close" let-d="dismiss">
    <div class="modal-header">
      <h4 class="modal-title" id="modal-basic-title">Figure deletion</h4>
      <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p><strong>Are you sure you want to delete this figure?</strong></p>
      <p>All information associated to this figure will be permanently deleted.
      <span class="text-danger">This operation can not be undone.</span>
      </p>  </div>
    <div class="modal-footer">
  
      <button type="button" class="btn btn-outline-secondary" (click)="c('Close click')">Cancel</button>
      <button type="button" class="btn btn-outline-danger" (click)='deleteFigures()' [disabled]='showDeleteSpinner'>
        Delete
        <span *ngIf='showDeleteSpinner' class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      </button>
    </div>
  </ng-template>

// Roman/React/src/pages/Figures/Figures.jsx
import React, { Component } from 'react';

import {Button, Alert} from 'react-bootstrap';

import './Figures.css';
import Spinner from '../../components/Spinner/Spinner';
import DelModal from '../../components/DelModal/DelModal';
import APP from '../../App-constants';

class Figures extends Component{
  
  

  constructor(props) {
    super(props);
    this.state = {
      items: [],
      isLoaded: false,
      deleteSuccess: false,
      showAlert: false,
      showDelModal: false,
      alertSuccessDeleteText: '',
    };

    this.modalDelClose = this.modalDelClose.bind(this);
  }

  componentDidMount() {
    fetch(`${APP.endpoints.baseUrl}${APP.endpoints.figures}`)
      .then(res => res.json())
      .then(json => {
        this.setState({
          isLoaded: true,
          items: json,
          currentIdDeleteFigure: Number
        })
      });
  }


  deleteFigures(id){
    this.setState({deleteSuccess: true});
    
    fetch(`${APP.endpoints.baseUrl}${APP.endpoints.figures}?id=${id}`, {
      method: 'DELETE'
    })
      .then(response => {
        if(response.ok){
          this.setState({deleteSuccess: false});
          var figures = this.state.items;
          var index = figures.findIndex(figure => figure.id === id);
          figures.splice(index,1);
          this.setState({items: figures});
          this.setState({ showDelModal: false })
          this.setState({alertSuccessDeleteText: `Figure number ${id} successfully removed`, showAlert: true});
        }
      });
  }

  modalDelClose() {
    this.setState({ showDelModal: false })
  }

  render(){

    var { isLoaded, items, deleteSuccess, showAlert, alertSuccessDeleteText, showDelModal, currentIdDeleteFigure } = this.state;

    if (!isLoaded) {
      return <Spinner />
    } else {
      items = items.sort((first,second) => first.area-second.area);
      return(
      <div className="container text-center table-responsive list-figures">

      {/* вынести в отдельный компонент
          https://ru.react.js.org/docs/conditional-rendering.html#Предотвращение-отрисовки-компонента
      */}
      {
        showAlert  &&
        <Alert dismissible variant="success" onClose={() => {this.setState({showAlert: false})}}>
          {alertSuccessDeleteText}
        </Alert>
      }
      


        <table className="table table-bordered table-hover table-striped">
          <caption>List added figures</caption>

          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">Type figures</th>
              <th scope="col">Area</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>

          <tbody>
            {
              items.map(figure => (
                <tr key={figure.id}>
                  <th scope="row"> {figure.id} </th>
                  <td> {figure.type} </td>
                  <td> {figure.area} </td>
                  <td> 
                    {/* спросить про байнд */}
                    <Button variant="outline-danger btn-sm" onClick={() => {this.setState({showDelModal: true, currentIdDeleteFigure: figure.id})}} disabled={deleteSuccess}>
                      Delete
                    </Button> 
                  </td>
                </tr>
              ))
            }
          </tbody>

        </table>

        {
          this.state.showDelModal &&
          <DelModal 
          show={showDelModal} 
          modalDelClose={this.modalDelClose} 
          deleteFigures={this.deleteFigures.bind(this, currentIdDeleteFigure)}
          deleteSuccess = {deleteSuccess}
          />
        }

      </div>
    );  
  }
  }
}

export default Figures;
