// Roman/React/src/components/Rectangle/Rectangle.jsx
import React, {Component} from 'react';

import {Button, Form} from 'react-bootstrap';

import './Rectangle.css';
import rectangleImg from '../../images/rectangle.png';
import APP from '../../App-constants';

class Rectangle extends Component{

  MINCOORDINATE = 0;
  MAXCOORDINATE = 1000;
  ACCURACY = 1000;
  INITIALX1 = 10; 
  INITIALY1 = 10; 
  INITIALX2 = 20; 
  INITIALY2 = 20; 
  STEP = 0.001;

  constructor(props) {
    super(props);
    this.state = {
      x1: this.INITIALX1,
      y1: this.INITIALY1,
      x2: this.INITIALX2,
      y2: this.INITIALY2,
      x1Valid: true,
      y1Valid: true,
      x2Valid: true,
      y2Valid: true,
    };

    this.handleChange = this.handleChange.bind(this);
    this.addRectangle = this.addRectangle.bind(this);
  }

  handleChange(event) {
    const target = event.target;
    const name = target.name;
    const value = target.value;
  
    this.setState({
      [name]: value,
    });

    if(value > this.MINCOORDINATE && value < this.MAXCOORDINATE){
      this.setState({
        [name+'Valid']: true
      });
    }
    else this.setState({
      [name+'Valid']: false
    });
  }

  getRectangleArea() {
    const x1 = this.state.x1;
    const y1 = this.state.y1;
    const x2 = this.state.x2;
    const y2 = this.state.y2;

    const a = x2-x1;
    const b = y2-y1;

    const area = Math.abs(a*b)
    return Math.round(area * this.ACCURACY)/this.ACCURACY;
  }

  addRectangle(event) {
    const area = this.getRectangleArea();
    this.props.addFigures(APP.types.rectangle, area, event);
  }

  render(){
    const {x1, y1, x2, y2, x1Valid, y1Valid, x2Valid, y2Valid} = this.state;

    return(
      <div className="container row">
        <div className="col-md-12 mb-12">

          <h3 className="text-center">Calculation of the area of a {APP.types.rectangle}</h3>
          <hr />

          <div className="row form-content">
            <Form className='col-md-6 mb-6'>
              <Form.Group controlId="formCoordinates">
                <div className='row'>
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Х1:</Form.Label>
                  <Form.Control 
                    className={x1Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP} 
                    name="x1" 
                    placeholder={this.INITIALX1}
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={x1} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !x1Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                </div>
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Y1:</Form.Label>
                  <Form.Control 
                    className={y1Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP}  
                    name="y1" 
                    placeholder={this.INITIALXY}
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={y1} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !y1Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                  </div>
                </div>

                <div className="row inputs-top">
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Х2:</Form.Label>
                  <Form.Control 
                    className={x2Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP}  
                    name="x2" 
                    placeholder={this.INITIALX2} 
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={x2} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !x2Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                </div>
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Y2:</Form.Label>
                  <Form.Control 
                    className={y2Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP}  
                    name="y2" 
                    placeholder={this.INITIALY2}
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={y2} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !y2Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                </div>
                </div>
              </Form.Group>

              <Button variant="success" type="submit" 
                disabled={!x1Valid || !y1Valid || !x2Valid || !y2Valid || this.props.responseIsSuccess}
                onClick={ (event) => this.addRectangle(event) }
              >
                Add a new {APP.types.rectangle}
                {
                  this.props.responseIsSuccess &&
                  <span className="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                }
              </Button>
            </Form>
    
          <div className="col-md-6 mb-6 text-center">
            <h4>
              Formulas: 
            </h4>
            <p className="h4">
              <code>
                S=ab
                <br />
                a=x2-x1
                <br />
                b=y2-y1
              </code>
            </p>
            <img src={rectangleImg} alt={APP.types.rectangle} height="100"/> 
          </div>

        </div>
      </div>
    </div>
    );
  }

}

export default Rectangle;

// Roman/Angular/src/app/rectangle/rectangle.component.ts
import { Component, EventEmitter, Output, Input } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

import { Figure } from '../models/figure';

@Component({
  selector: 'app-rectangle',
  templateUrl: 'rectangle.component.html',
  styleUrls: ['rectangle.component.css']
})

export class RectangleComponent{
  
  @Output() addFigureEvent = new EventEmitter<Figure>();
  @Input() responseIsSuccess: boolean;

  private rectangleControl : FormGroup;
  
  ngOnInit() {
    this.rectangleControl = new FormGroup({
      X1: new FormControl(10, [Validators.required]),
      Y1: new FormControl(10, [Validators.required]),
      X2: new FormControl(20, [Validators.required]),
      Y2: new FormControl(20, [Validators.required]),
    });
  }


  private addRectangle(): void {
    const area = this.getRectangleArea();

    this.addFigureEvent.emit({
      type: 'Rectangle',
      area: area
    })
  }

  public getRectangleArea(): number {
    const points = this.rectangleControl.value;

    const x1 = points['X1'];
    const y1 = points['Y1'];
    const x2 = points['X2'];
    const y2 = points['Y2'];

    const a = x2-x1;
    const b = y2-y1;

    return Math.abs(a*b);
  }

}
<form class="needs-validation" novalidate [formGroup]='rectangleControl'>
  <div class="form-row">
    <div class="col-md-12 mb-12">

      <h3 class="text-center">Calculation of the area of a rectangle</h3>
      <hr />

      <div id='form-content' class="form-row">
        <div class="col-md-6 mb-6">
          <div class="form-row">
            <div class="col-md-6 mb-6">
              <label for="X1">Coordinate Х1:</label>
              <input type="number" class="form-control" id="X1" placeholder="100" formControlName = 'X1' required>
              <div *ngIf="rectangleControl.controls['X1'].invalid && rectangleControl.controls['X1'].errors.required" class="alert alert-danger">
                Obligatory field.
              </div>
            </div>
            <div class="col-md-6 mb-6">
              <label for="Y1">Coordinate Y1:</label>
              <input type="number" class="form-control" id="Y1" placeholder="100" formControlName = 'Y1' required>
              <div *ngIf="rectangleControl.controls['Y1'].invalid && rectangleControl.controls['Y1'].errors.required" class="alert alert-danger">
                Obligatory field.
              </div>
            </div>
          </div>
          <div class="form-row inputs-top">
            <div class="col-md-6 mb-6">
              <label for="X2">Coordinate Х2:</label>
              <input type="number" class="form-control" id="X2" placeholder="100" formControlName = 'X2' required>
              <div *ngIf="rectangleControl.controls['X2'].invalid && rectangleControl.controls['X2'].errors.required" class="alert alert-danger">
                Obligatory field.
              </div>
            </div>
            <div class="col-md-6 mb-6">
              <label for="Y2">Coordinate Y2:</label>
              <input type="number" class="form-control" id="Y2" placeholder="100" formControlName = 'Y2' required>
              <div *ngIf="rectangleControl.controls['Y2'].invalid && rectangleControl.controls['Y2'].errors.required" class="alert alert-danger">
                Obligatory field.
              </div>
            </div>
        </div>
        <button id='btn-add' class="btn btn-primary" type="submit" (click)='addRectangle()' [disabled]="rectangleControl.invalid || responseIsSuccess">
          Add a new rectangle
          <span *ngIf='responseIsSuccess' class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        </button>
      </div>
  
        <div class="col-md-6 mb-6 text-center">
          <h4>
            Formulas: 
          </h4>
          <p class="h4">
            <code>
              S=ab
              <br>
              a=x2-x1
              <br>
              b=y2-y1
            </code>
          </p>
          <img src="../../assets/Images/rectangle.png" alt="rectangle" height="100"> 
        </div>

      </div>
    </div>
  </div>
</form>
