// Roman/Vue.js/src/App.vue
<template>
  <div id="app">
    <header>
      <Header />
    </header>
    <main>
      <router-view></router-view>
    </main>
    
  </div>
</template>

<script>
import Header from '@/components/Header.vue'

export default {
  name: 'app',
  components: {
    Header
  },
  watch: {
    $route(to) {
        document.title = to.meta.title || 'Figures';
    },
  }
}
</script>

// Roman/React/src/App.js
import React, { Component, Suspense } from 'react';
import {BrowserRouter as Router }  from 'react-router-dom';

import './App.css';

import Header from './components/Header/Header';
import Main from './components/Main/Main';
import Spinner from './components/Spinner/Spinner'


class App extends Component {
  render() {
    return (
      <Router>
        <Suspense fallback={<Spinner />}>
          <Header />
          <Main />
        </Suspense>
      </Router>
    );
  }
}

export default App;
