// Roman/Vue.js/src/components/Figures/Rectangle/RectangleComponent.vue
<template>
  <div class="container row">
    <div class="col-md-12 mb-12">

      <TitleMessage :typeFigures='APP.types.rectangle'></TitleMessage>

      <div class="row form-content">

        <div class='col-md-6 mb-6'>
          <b-form @submit="addRectangle" class="form-row">

            <div class="form-row">
              <div class="col-md-6 mb-6">
                <label for="x1" class="text-left">Coordinate Х1:</label>
                <b-form-input 
                  id='x1' 
                  v-model.number='x1'
                  type='number'
                  placeholder='10' 
                  :min='minCoordinate' 
                  :max='maxCoordinate' 
                  step='0.1'   
                  :state="x1State"
                ></b-form-input>
                <b-form-invalid-feedback id="input-live-feedback" class="text-left">
                  Plese enter valid coordinate
                </b-form-invalid-feedback>
              </div>
              
              <div class="col-md-6 mb-6">
                <label for="y1" class="text-left">Coordinate Y1:</label>
                <b-form-input 
                  id='y1' 
                  v-model.number='y1'
                  type='number'
                  placeholder='10' 
                  :min='minCoordinate' 
                  :max='maxCoordinate' 
                  step='0.1'   
                  :state="y1State"
                ></b-form-input>
                <b-form-invalid-feedback id="input-live-feedback" class="text-left">
                  Plese enter valid coordinate
                </b-form-invalid-feedback>
              </div>
            </div>

            <div class="form-row inputs-top">
              <div class="col-md-6 mb-6">
                <label for="x2" class="text-left">Coordinate Х2:</label>
                <b-form-input 
                  id='x2' 
                  v-model.number='x2'
                  type='number'
                  placeholder='20' 
                  :min='minCoordinate' 
                  :max='maxCoordinate' 
                  step='0.1'   
                  :state="x2State"
                ></b-form-input>
                <b-form-invalid-feedback id="input-live-feedback" class="text-left">
                  Plese enter valid coordinate
                </b-form-invalid-feedback>
              </div>

              <div class="col-md-6 mb-6">
                <label for="y2" class="text-left">Coordinate Y2:</label>
                <b-form-input 
                  id='y2' 
                  v-model.number='y2'
                  type='number'
                  placeholder='20' 
                  :min='minCoordinate' 
                  :max='maxCoordinate' 
                  step='0.1'   
                  :state="y2State"
                ></b-form-input>
                <b-form-invalid-feedback id="input-live-feedback" class="text-left">
                  Plese enter valid coordinate
                </b-form-invalid-feedback>
              </div>
            </div>

            <b-button 
              type="submit"
              class="add-rectangle-button"
              :variant='x1State && y1State && x2State && y2State ? "success": "danger"' 
              :disabled='!x1State || !y1State || !x2State || !y2State || responseIsSuccess'
            >
              Add new {{ APP.types.rectangle }}
              <ButtonSpinner v-if="responseIsSuccess"></ButtonSpinner>
            </b-button>         

          </b-form>
        </div>
        
        <div class="col-md-6 mb-6 text-center">
          <FiguresInformation formula='S=a·b' imageName='rectangle.png'></FiguresInformation>
        </div>
        
      </div>
      
    </div>
  </div>
</template>

<script>
import TitleMessage from '@/components/Figures/TitleMessage'
import FiguresInformation from '@/components/Figures/FiguresInformation'
import ButtonSpinner from '@/components/ButtonSpinner'
import { APP } from '@/application-constants'

export default {
  name: 'Rectangle',
  components: {
    TitleMessage,
    FiguresInformation,
    ButtonSpinner
  },
  props: ['responseIsSuccess'],
  data() {
    return {
      x1: 10,
      y1: 10,
      x2: 20,
      y2: 20,
      minCoordinate: -10000,
      maxCoordinate: 10000,
      APP
    }
  },
  computed: {
    x1State() {
      if (this.x1 > this.minCoordinate && this.x1 <= this.maxCoordinate && this.x1 != 0) {
        return true;
      }
      return false
    },
    y1State() {
      if (this.y1 > this.minCoordinate && this.y1 <= this.maxCoordinate && this.y1 != 0) {
        return true;
      }
      return false
    },
    x2State() {
      if (this.x2 > this.minCoordinate && this.x2 <= this.maxCoordinate && this.x2 != 0) {
        return true;
      }
      return false
    },
    y2State() {
      if (this.y2 > this.minCoordinate && this.y2 <= this.maxCoordinate && this.y2 != 0) {
        return true;
      }
      return false
    },
  },

  methods: {

    getRectangleArea() {
      const a = Number(this.x2) - Number(this.x1);
      const b = Number(this.y2) - Number(this.y1);
      const area = Math.abs(a*b);
      return Math.round(area * 10000)/10000;
    },

    addRectangle(evt) {
      evt.preventDefault();
      const area = this.getRectangleArea();
      const data = {
        x1: this.x1,
        y1: this.y1,
        x2: this.x2,
        y2: this.y2,
      }
      this.$emit('addFigures', APP.types.rectangle, area, data);
    },
    
  }
  
}
</script>

<style scope>
  .form-content{
    margin: 25px;
  }
  .text-left{
    float: left;
  }
  .inputs-top{
    margin-top: 15px;
  }
  .add-rectangle-button{
    margin-top: 15px;
  }
</style>

// Roman/React/src/components/Rectangle/Rectangle.jsx
import React, {Component} from 'react';

import {Button, Form} from 'react-bootstrap';

import './Rectangle.css';
import rectangleImg from '../../images/rectangle.png';
import APP from '../../App-constants';

class Rectangle extends Component{

  MINCOORDINATE = 0;
  MAXCOORDINATE = 1000;
  ACCURACY = 1000;
  INITIALX1 = 10; 
  INITIALY1 = 10; 
  INITIALX2 = 20; 
  INITIALY2 = 20; 
  STEP = 0.001;

  constructor(props) {
    super(props);
    this.state = {
      x1: this.INITIALX1,
      y1: this.INITIALY1,
      x2: this.INITIALX2,
      y2: this.INITIALY2,
      x1Valid: true,
      y1Valid: true,
      x2Valid: true,
      y2Valid: true,
    };

    this.handleChange = this.handleChange.bind(this);
    this.addRectangle = this.addRectangle.bind(this);
  }

  handleChange(event) {
    const target = event.target;
    const name = target.name;
    const value = target.value;
  
    this.setState({
      [name]: value,
    });

    if(value > this.MINCOORDINATE && value < this.MAXCOORDINATE){
      this.setState({
        [name+'Valid']: true
      });
    }
    else this.setState({
      [name+'Valid']: false
    });
  }

  getRectangleArea() {
    const x1 = this.state.x1;
    const y1 = this.state.y1;
    const x2 = this.state.x2;
    const y2 = this.state.y2;

    const a = x2-x1;
    const b = y2-y1;

    const area = Math.abs(a*b)
    return Math.round(area * this.ACCURACY)/this.ACCURACY;
  }

  addRectangle(event) {
    const area = this.getRectangleArea();
    this.props.addFigures(APP.types.rectangle, area, event);
  }

  render(){
    const {x1, y1, x2, y2, x1Valid, y1Valid, x2Valid, y2Valid} = this.state;

    return(
      <div className="container row">
        <div className="col-md-12 mb-12">

          <h3 className="text-center">Calculation of the area of a {APP.types.rectangle}</h3>
          <hr />

          <div className="row form-content">
            <Form className='col-md-6 mb-6'>
              <Form.Group controlId="formCoordinates">
                <div className='row'>
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Х1:</Form.Label>
                  <Form.Control 
                    className={x1Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP} 
                    name="x1" 
                    placeholder={this.INITIALX1}
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={x1} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !x1Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                </div>
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Y1:</Form.Label>
                  <Form.Control 
                    className={y1Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP}  
                    name="y1" 
                    placeholder={this.INITIALXY}
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={y1} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !y1Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                  </div>
                </div>

                <div className="row inputs-top">
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Х2:</Form.Label>
                  <Form.Control 
                    className={x2Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP}  
                    name="x2" 
                    placeholder={this.INITIALX2} 
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={x2} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !x2Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                </div>
                <div className="col-md-6 mb-6">
                  <Form.Label>Coordinate Y2:</Form.Label>
                  <Form.Control 
                    className={y2Valid?'is-valid':'is-invalid'}
                    type="number" 
                    step={this.STEP}  
                    name="y2" 
                    placeholder={this.INITIALY2}
                    min={this.MINCOORDINATE} 
                    max={this.MAXCOORDINATE} 
                    value={y2} 
                    onChange={this.handleChange} 
                    required 
                  />
                  {
                    !y2Valid && <div className='alert alert-danger'>
                      Incorrect coordinate
                    </div>
                  }
                </div>
                </div>
              </Form.Group>

              <Button variant="success" type="submit" 
                disabled={!x1Valid || !y1Valid || !x2Valid || !y2Valid || this.props.responseIsSuccess}
                onClick={ (event) => this.addRectangle(event) }
              >
                Add a new {APP.types.rectangle}
                {
                  this.props.responseIsSuccess &&
                  <span className="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                }
              </Button>
            </Form>
    
          <div className="col-md-6 mb-6 text-center">
            <h4>
              Formulas: 
            </h4>
            <p className="h4">
              <code>
                S=ab
                <br />
                a=x2-x1
                <br />
                b=y2-y1
              </code>
            </p>
            <img src={rectangleImg} alt={APP.types.rectangle} height="100"/> 
          </div>

        </div>
      </div>
    </div>
    );
  }

}

export default Rectangle;
