// Roman/Vue.js/src/components/Header.vue
<template>
  <b-navbar toggleable="lg" type="dark" variant="primary">
  <div class="container">
    <router-link class="navbar-brand" to="/">Figures</router-link>
    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav>
        <li class="nav-item">
          <router-link class="nav-link" to="/" exact>List</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" :to='APP.routes.pathAddFigures'>Add</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" :to='APP.routes.pathStatistics'>Statistics</router-link>
        </li>
      </b-navbar-nav>

    </b-collapse>
  </div>
  </b-navbar>
</template>

<script>
import { APP } from '@/application-constants'

export default {
  name: 'Header',
  data(){
    return{
      APP
    }
  }
}
</script>

<style>

</style>

// Roman/React/src/components/Header/Header.jsx
import React, { Component } from 'react';
import { NavLink } from 'react-router-dom';

import './Header.css';

class Header extends Component{
  render(){
    return(
      <header>
        <nav className="navbar navbar-dark navbar-expand-lg bg-primary">
          <div className="container">
            <NavLink className="navbar-brand" to='/'>Figures</NavLink>
            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div id="navbarText" className="collapse navbar-collapse text-center">
              <ul className="navbar-nav ml-auto">
                <li className="nav-item">
                  <NavLink exact={true} to='/' activeClassName='active' className="nav-link">List figures</NavLink>
                </li>
                <li className="nav-item">
                  <NavLink to='/AddFigures' activeClassName='active' className="nav-link">Add figures</NavLink>
                </li>
                <li className="nav-item">
                  <NavLink to='/Statistics' activeClassName='active' className="nav-link">Statistics</NavLink>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

    );
  }
}

export default Header;
