// Roman/React/src/components/Triangle/Triangle.jsx
import React, {Component} from 'react';

import {Button, Form, Alert} from 'react-bootstrap/';

import './Triangle.css';
import triangleImg from '../../images/triangle.png';
import APP from '../../App-constants';

class Triangle extends Component {

  MINLENGTH = 0;
  MAXLENGTH = 1000;
  ACCURACY = 1000;
  INITIALLENGTH1 = 3;
  INITIALLENGTH2 = 4;
  INITIALLENGTH3 = 5;
  STEP = 0.001;

  constructor(props) {
    super(props);
    this.state = {
      length1: this.INITIALLENGTH1,
      length2: this.INITIALLENGTH2,
      length3: this.INITIALLENGTH3,
      length1Valid: true,
      length2Valid: true,
      length3Valid: true,
      triangleValid: true
    };

    this.handleChange = this.handleChange.bind(this);
    this.addTriangle = this.addTriangle.bind(this);
  }

  handleChange(event) {
    const target = event.target;
    const name = target.name;
    const value = target.value;
  
    this.setState({
      [name]: value,
    });

    let names = ['length1', 'length2', 'length3'];
    names = names.filter( item => item !== name );

    const a = Number(value);
    const b = Number(this.state[names[0]]);
    const c = Number(this.state[names[1]]); 

    if(value > this.MINLENGTH && value < this.MAXLENGTH){
      this.setState({
        [name+'Valid']: true
      });
      
      if (a<b+c && b<a+c && c<a+b){
        this.setState({triangleValid: true});
      }
      else this.setState({triangleValid: false});
    }
    else {
      this.setState({
        [name+'Valid']: false
      });
      return;
    };    
  }

  getTriangleArea() {
    const a = this.state.length1;
    const b = this.state.length2;
    const c = this.state.length3;

    const p = (a+b+c)/2;
    let area = Math.sqrt(p*(p-a)*(p-b)*(p-c));
    return Math.round(area * this.ACCURACY)/this.ACCURACY;
  }

  addTriangle(event) {
    const area = this.getTriangleArea();
    this.props.addFigures(APP.types.triangle, area, event);        
  }

  render(){
    const {length1, length2, length3, length1Valid, length2Valid, length3Valid, triangleValid} = this.state;
    return(
      <div className="container row">
        <div className="col-md-12 mb-12">

          <h3 className="text-center">Calculation of the area of a {APP.types.triangle}</h3>
          <hr />

          <div className="row form-content">
            <Form className='col-md-6 mb-6'>
              <Form.Group controlId="formLengths">
                
                <Form.Label>Side length 1:</Form.Label>
                <Form.Control 
                  className={length1Valid && triangleValid?'is-valid':'is-invalid'}
                  type="number" 
                  step={this.STEP} 
                  name="length1" 
                  placeholder={this.INITIALLENGTH1} 
                  min={this.minCoordinate} 
                  max={this.maxCoordinate} 
                  value={length1} 
                  onChange={this.handleChange} 
                  required 
                />
                {
                  !length1Valid && <div className='alert alert-danger'>
                    Incorrect length
                  </div>
                }

                <Form.Label className='triangle-label'>Side length 2:</Form.Label>
                <Form.Control 
                  className={length2Valid && triangleValid?'is-valid':'is-invalid'}
                  type="number" 
                  step={this.STEP}  
                  name="length2" 
                  placeholder={this.INITIALLENGTH2}
                  min={this.minCoordinate} 
                  max={this.maxCoordinate} 
                  value={length2} 
                  onChange={this.handleChange} 
                  required 
                />
                {
                  !length2Valid && <div className='alert alert-danger'>
                    Incorrect length
                  </div>
                }

                <Form.Label className='triangle-label'>Side length 3:</Form.Label>
                <Form.Control 
                  className={length3Valid && triangleValid?'is-valid':'is-invalid'}
                  type="number" 
                  step={this.STEP} 
                  name="length3" 
                  placeholder={this.INITIALLENGTH3}
                  min={this.minCoordinate} 
                  max={this.maxCoordinate} 
                  value={length3} 
                  onChange={this.handleChange} 
                  required 
                />
                {
                  !length3Valid && <div className='alert alert-danger'>
                    Incorrect length
                  </div>
                }
                </Form.Group>


                <Button variant="success" type="submit" 
                disabled={!length1Valid || !length2Valid || !length3Valid || !triangleValid || this.props.responseIsSuccess}
                onClick={ (event) => this.addTriangle(event)}
                >
                  Add a new {APP.types.triangle}
                  {
                    this.props.responseIsSuccess &&
                    <span className="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                  }
                </Button>
              </Form>


            <div className="col-md-6 mb-6 text-center">
              <h4>
                Formula:
                <br />
                <code>S=√(p·(p-a)·(p-b)·(p-c))</code>
              </h4>    
              <img src={triangleImg} alt={APP.types.triangle} height="100"/> 
            </div>

          </div>

          {
            !triangleValid && 
            <Alert variant="danger" className='text-center'>
              I can not build a triangle with such a side
            </Alert>
          }

        </div>
      </div>
    );
  }
}

export default Triangle;

// Roman/Vue.js/src/components/Figures/Triangle/TriangleComponent.vue
<template>
  <div class="container row">
    <div class="col-md-12 mb-12">

      <TitleMessage :typeFigures='APP.types.triangle'></TitleMessage>

      <div class="row form-content">

        <div class='col-md-6 mb-6'>
          <b-form @submit="addTriangle" class="form-row">

            <b-form-group>
            <label for='length1' class="text-left">Side length 1:</label>
            <b-form-input 
              id='length1' 
              v-model.number='length1'
              type='number'
              placeholder='3' 
              :min='minLength' 
              :max='maxLength' 
              step='0.1'   
              :state="length1State && triangleIsValid"
            ></b-form-input>
            <b-form-invalid-feedback id="input-live-feedback" class="text-left">
              Plese enter valid length
            </b-form-invalid-feedback>
            </b-form-group>

            <b-form-group>
            <label for='length2' class="text-left">Side length 2:</label>
            <b-form-input 
              id='length2' 
              v-model.number='length2'
              type='number'
              placeholder='4' 
              :min='minLength' 
              :max='maxLength' 
              step='0.1'   
              :state="length2State && triangleIsValid"
            ></b-form-input>
            <b-form-invalid-feedback id="input-live-feedback" class="text-left">
              Plese enter valid length
            </b-form-invalid-feedback>
            </b-form-group>

            <b-form-group>
            <label for='length3' class="text-left">Side length 3:</label>
            <b-form-input 
              id='length3' 
              v-model.number='length3'
              type='number'
              placeholder='5' 
              :min='minLength' 
              :max='maxLength' 
              step='0.1'   
              :state="length3State && triangleIsValid"
            ></b-form-input>
            <b-form-invalid-feedback id="input-live-feedback" class="text-left">
              Plese enter valid length
            </b-form-invalid-feedback>
            </b-form-group>

            <b-button 
              type="submit"
              class="add-triangle-button"
              :variant='length1State && length2State && length3State && triangleIsValid ? "success": "danger"' 
              :disabled='!length1State || !length2State || !length3State || !triangleIsValid || responseIsSuccess'
            >
              Add new {{ APP.types.triangle }}
              <ButtonSpinner v-if="responseIsSuccess"></ButtonSpinner>
            </b-button>

          </b-form>
        </div>
        
        <div class="col-md-6 mb-6 text-center">
          <FiguresInformation formula='S=√(p·(p-a)·(p-b)·(p-c))' imageName='triangle.png'></FiguresInformation>
        </div>

      </div>
      
      <b-alert v-if="!triangleIsValid" variant="danger" show class="dangerAlert text-center">I can not build a triangle with such a side</b-alert>


    </div>
  </div>
</template>

<script>
import TitleMessage from '@/components/Figures/TitleMessage'
import FiguresInformation from '@/components/Figures/FiguresInformation'
import ButtonSpinner from '@/components/ButtonSpinner'
import { APP } from '@/application-constants'

export default {
  name: 'Triangle',
  components: {
    TitleMessage,
    FiguresInformation,
    ButtonSpinner
  },
  props: ['responseIsSuccess'],
  data() {
    return {
      length1: 3,
      length2: 4,
      length3: 5,
      minLength: 0,
      maxLength: 10000,
      APP
    }
  },
  computed: {
    length1State() {
      if (this.length1 > this.minLength && this.length1 <= this.maxLength) {
        return true;
      }
      return false
    },
    length2State() {
      if (this.length2 > this.minLength && this.length2 <= this.maxLength) {
        return true;
      }
      return false
    },
    length3State() {
      if (this.length3 > this.minLength && this.length3 <= this.maxLength) {
        return true;
      }
      return false
    },
    triangleIsValid(){
      if (this.length1+this.length2<=this.length3 || this.length1+this.length3<=this.length2 || this.length2+this.length3<=this.length1){
        return false;
      }
      return true;
    }
  },
  methods: {

    getTriangleArea() {
      const p = (Number(this.length1) + Number(this.length2) + Number(this.length3))/2;
      const area = Math.sqrt(p * ( p - Number(this.length1) ) * ( p - Number(this.length2) ) * ( p - Number(this.length3) ) );
      return Math.round(area * 10000)/10000;
    },

    addTriangle(evt) {
      evt.preventDefault();
      const area = this.getTriangleArea();
      const data = {
        length1: this.length1,
        length2: this.length2,
        length3: this.length3,
      }
      this.$emit('addFigures', APP.types.triangle, area, data);
    },
    
  }
}
</script>

<style scope>

  .form-content{
    margin: 25px;
  }
  .dangerAlert{
    margin: 0 50px;
  }

</style>
