// Roman/Vue.js/src/components/Spinner.vue
<template>
  <div class="spinner-section">
    <b-spinner variant="primary" label="Loading..."></b-spinner>
  </div>
</template>

<script>
export default {
  name: 'Spinner',
}
</script>

<style scoped>
  .spinner-section{
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    position: fixed;
  }
</style>

// Roman/React/src/components/Spinner/Spinner.jsx
import React, { Component } from 'react';
import './Spinner.css';

class Spinner extends Component {
  render () {
    return (
      <div className="d-flex justify-content-center align-items-center spinner">
        <div className="spinner-border text-primary" role="status">
          <span className="sr-only">Loading...</span>
        </div>
      </div>
    );
  }
}

export default Spinner;
