// Roman/React/src/pages/Statistics/Statistics.jsx
import React, { Component } from 'react';

import ProgressBar from 'react-bootstrap/ProgressBar'

import './Statistics.css';
import Spinner from '../../components/Spinner/Spinner'
import APP from '../../App-constants';

class Statistics extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      items: [],
      isLoaded: false,
      statistic: [],
    }
  }

  componentDidMount() {
    fetch(`${APP.endpoints.baseUrl}${APP.endpoints.figures}`)
      .then(res => res.json())
      .then(json => {
        this.setState({
          isLoaded: true,
          items: json,
        })
      });
  }
  
  getStatistic(items){

    let totalArea = 0; 
    let circlesArea = 0; 
    let squaresArea = 0; 
    let rectanglesArea = 0; 
    let trianglesArea = 0; 

    const Circles = items.filter(figure => figure.type === APP.types.circle); 
    for (let item of Circles){ 
      circlesArea += item.area; 
      totalArea += item.area; 
    } 

    const Squares = items.filter(figure => figure.type === APP.types.square); 
    for (let item of Squares){ 
      squaresArea += item.area; 
      totalArea += item.area; 
    } 

    const Rectangles = items.filter(figure => figure.type === APP.types.rectangle); 
    for (let item of Rectangles){ 
      rectanglesArea += item.area; 
      totalArea += item.area; 
    } 

    const Triangles = items.filter(figure => figure.type === APP.types.triangle); 
    for (let item of Triangles){ 
      trianglesArea += item.area; 
      totalArea += item.area; 
    } 

    const circlePercent = 100*circlesArea/totalArea; 
    const squarePercent = 100*squaresArea/totalArea; 
    const rectanglePercent = 100*rectanglesArea/totalArea; 
    const trianglePercent = 100*trianglesArea/totalArea; 

    let statistic = [
      {
        type: APP.types.circle,
        area: circlesArea,
        percent: Math.round(circlePercent * 1000) / 1000 
      },
      {
        type: APP.types.square,
        area: squaresArea,
        percent: Math.round(squarePercent * 1000) / 1000 
      },
      {
        type: APP.types.rectangle,
        area: rectanglesArea,
        percent:  Math.round(rectanglePercent * 1000) / 1000  
      },
      {
        type: APP.types.triangle,
        area: trianglesArea,
        percent:  Math.round(trianglePercent * 1000) / 1000 
      },
    ]
    
    return statistic;
  }

  checkType(type){
    switch (type) {
      case APP.types.circle:
        return 'warning';

      case APP.types.square:
        return 'danger';

      case APP.types.rectangle:
        return 'primary';

      case APP.types.triangle:
        return 'success'; 

      default:
        return 'secondary';
    }

  }

  render(){
    
    var { isLoaded, items } = this.state;

    if (!isLoaded) {
      return <Spinner />
    } else {
      let statistic = this.getStatistic(items);

      return(
        <div className="container text-center statistic">
          <table className="table table-striped table-bordered table-hover">
            <caption>Statistics of added figures</caption>

            <thead>
              <tr>
                <th scope="col">Type figures</th>
                <th scope="col">Total area</th>
                <th scope="col">Percent of total area</th>
              </tr>
            </thead>
            
            <tbody>
              {
                statistic.map(figure  => (
                  <tr key={figure.type}>
                    <td> { figure.type } </td>
                    <td> { figure.area }</td>
                    <td> { figure.percent }%</td>
                  </tr>
                ))
              }
              
            </tbody>

          </table>

          <div>
            {
              statistic.map(figure => (
                <ProgressBar key={figure.type} className='progressBar' animated variant={this.checkType(figure.type)} now={figure.percent} label={`${figure.type}: ${figure.percent}%`}/>
              ))
            }
          </div>

        </div>
      );
    }
  }
}

export default Statistics;

// Roman/Angular/src/app/statistics/statistics.component.ts
import { Component } from '@angular/core';

import { Figure } from '../models/figure';
import { FigureService } from '../services/figure.service';

@Component({
  selector: 'app-statistics',
  templateUrl: './statistics.component.html',
  styleUrls: ['./statistics.component.css'],
})

export class StatisticsComponent {
  public showSpinner: boolean = true;
  public figures: Figure[];
  public statistic: {}[];

  constructor (
    private figureService: FigureService
  ) {}

  ngOnInit() {
    this.getFigures()
  }
  
  private getFigures(): void {
    this.figureService.getFigures()
      .subscribe(figures => {
        this.figures = figures;
        this.getStatistic();
      });
  }
  
  public getStatistic(): void{
    let totalArea = 0; 
    let circlesArea = 0; 
    let squaresArea = 0; 
    let rectanglesArea = 0; 
    let trianglesArea = 0; 

    const Circles = this.figures.filter(figure => figure.type === 'Circle'); 
    for (let item of Circles){ 
      circlesArea += item.area; 
      totalArea += item.area; 
    } 

    const Squares = this.figures.filter(figure => figure.type === 'Square'); 
    for (let item of Squares){ 
      squaresArea += item.area; 
      totalArea += item.area; 
    } 

    const Rectangles = this.figures.filter(figure => figure.type === 'Rectangle'); 
    for (let item of Rectangles){ 
      rectanglesArea += item.area; 
      totalArea += item.area; 
    } 

    const Triangles = this.figures.filter(figure => figure.type === 'Triangle'); 
    for (let item of Triangles){ 
      trianglesArea += item.area; 
      totalArea += item.area; 
    } 

    const circlePercent = 100*circlesArea/totalArea; 
    const squarePercent = 100*squaresArea/totalArea; 
    const rectanglePercent = 100*rectanglesArea/totalArea; 
    const trianglePercent = 100*trianglesArea/totalArea; 

    this.statistic = [
      {
        type: 'Circle',
        area: circlesArea,
        percent: Math.round(circlePercent * 1000) / 1000 
      },
      {
        type: 'Square',
        area: squaresArea,
        percent: Math.round(squarePercent * 1000) / 1000 
      },
      {
        type: 'Rectangle',
        area: rectanglesArea,
        percent:  Math.round(rectanglePercent * 1000) / 1000  
      },
      {
        type: 'Triangle',
        area: trianglesArea,
        percent:  Math.round(trianglePercent * 1000) / 1000 
      },
    ]

    this.showSpinner = false;

  }

  public checkType(type: string){
    switch (type) {
      case 'Circle':
        return 'warning';

      case 'Square':
        return 'danger';

      case 'Rectangle':
        return 'primary';

      case 'Triangle':
        return 'success'; 

      default:
        return 'secondary';
    }

  }

}

<div *ngIf='showSpinner' class="d-flex justify-content-center align-items-center spinner">
  <div class="spinner-border text-primary" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<div *ngIf='!showSpinner' class="container text-center statistic">
  <table class="table table-striped table-bordered table-hover">
    <caption>Statistics of added figures</caption>

    <thead>
      <tr>
        <th scope="col">Type figures</th>
        <th scope="col">Total area</th>
        <th scope="col">Percent of total area</th>
      </tr>
    </thead>
    
    <tbody>
      <tr *ngFor="let item of statistic">
        <td> {{ item.type }} </td>
        <td> {{ item.area | number }}</td>
        <td> {{ item.percent | number }}%</td>
      </tr>
    </tbody>

  </table>

  <div *ngFor='let item of statistic'>
    <p><ngb-progressbar [type]="checkType(item.type)" [value]="item.percent" [striped]="true" [animated]="true" height="35px"><p class="text-progressbar">{{item.type}}: {{item.percent}}%</p></ngb-progressbar></p>
  </div>

</div>
