// Roman/React/src/pages/Statistics/Statistics.jsx
import React, { Component } from 'react';

import ProgressBar from 'react-bootstrap/ProgressBar'

import './Statistics.css';
import Spinner from '../../components/Spinner/Spinner'
import APP from '../../App-constants';

class Statistics extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      items: [],
      isLoaded: false,
      statistic: [],
    }
  }

  componentDidMount() {
    fetch(`${APP.endpoints.baseUrl}${APP.endpoints.figures}`)
      .then(res => res.json())
      .then(json => {
        this.setState({
          isLoaded: true,
          items: json,
        })
      });
  }
  
  getStatistic(items){

    let totalArea = 0; 
    let circlesArea = 0; 
    let squaresArea = 0; 
    let rectanglesArea = 0; 
    let trianglesArea = 0; 

    const Circles = items.filter(figure => figure.type === APP.types.circle); 
    for (let item of Circles){ 
      circlesArea += item.area; 
      totalArea += item.area; 
    } 

    const Squares = items.filter(figure => figure.type === APP.types.square); 
    for (let item of Squares){ 
      squaresArea += item.area; 
      totalArea += item.area; 
    } 

    const Rectangles = items.filter(figure => figure.type === APP.types.rectangle); 
    for (let item of Rectangles){ 
      rectanglesArea += item.area; 
      totalArea += item.area; 
    } 

    const Triangles = items.filter(figure => figure.type === APP.types.triangle); 
    for (let item of Triangles){ 
      trianglesArea += item.area; 
      totalArea += item.area; 
    } 

    const circlePercent = 100*circlesArea/totalArea; 
    const squarePercent = 100*squaresArea/totalArea; 
    const rectanglePercent = 100*rectanglesArea/totalArea; 
    const trianglePercent = 100*trianglesArea/totalArea; 

    let statistic = [
      {
        type: APP.types.circle,
        area: circlesArea,
        percent: Math.round(circlePercent * 1000) / 1000 
      },
      {
        type: APP.types.square,
        area: squaresArea,
        percent: Math.round(squarePercent * 1000) / 1000 
      },
      {
        type: APP.types.rectangle,
        area: rectanglesArea,
        percent:  Math.round(rectanglePercent * 1000) / 1000  
      },
      {
        type: APP.types.triangle,
        area: trianglesArea,
        percent:  Math.round(trianglePercent * 1000) / 1000 
      },
    ]
    
    return statistic;
  }

  checkType(type){
    switch (type) {
      case APP.types.circle:
        return 'warning';

      case APP.types.square:
        return 'danger';

      case APP.types.rectangle:
        return 'primary';

      case APP.types.triangle:
        return 'success'; 

      default:
        return 'secondary';
    }

  }

  render(){
    
    var { isLoaded, items } = this.state;

    if (!isLoaded) {
      return <Spinner />
    } else {
      let statistic = this.getStatistic(items);

      return(
        <div className="container text-center statistic">
          <table className="table table-striped table-bordered table-hover">
            <caption>Statistics of added figures</caption>

            <thead>
              <tr>
                <th scope="col">Type figures</th>
                <th scope="col">Total area</th>
                <th scope="col">Percent of total area</th>
              </tr>
            </thead>
            
            <tbody>
              {
                statistic.map(figure  => (
                  <tr key={figure.type}>
                    <td> { figure.type } </td>
                    <td> { figure.area }</td>
                    <td> { figure.percent }%</td>
                  </tr>
                ))
              }
              
            </tbody>

          </table>

          <div>
            {
              statistic.map(figure => (
                <ProgressBar key={figure.type} className='progressBar' animated variant={this.checkType(figure.type)} now={figure.percent} label={`${figure.type}: ${figure.percent}%`}/>
              ))
            }
          </div>

        </div>
      );
    }
  }
}

export default Statistics;

// Roman/Vue.js/src/pages/Statistics.vue
<template>

  <Spinner v-if='!getFiguresIsSuccess'></Spinner>

  <div v-else class="container statistics-section">

    <NoFiguresAlert v-if="figures.length === 0"></NoFiguresAlert>

    <div v-else class="text-center">
      <b-table 
        bordered
        hover
        striped
        fixed
        caption-top
        :fields="fields"
        :items="getStatistics"
      >
        <template slot="table-caption">Statistics</template>
        <template slot="percent" slot-scope="data">
          {{ data.item.percent }}%
        </template>
        
      </b-table>

      <div class="mt-4">
        <b-progress 
          v-for="(item, index) in getStatistics" 
          :key="index" 
          :variant="checkType(item.type)"
          show-progress 
          striped 
          animated 
          height="25px" 
          class="mb-3 progress-text"
        >
          <b-progress-bar 
            :value="item.percent" 
          >
            <strong>{{item.type}}: {{item.percent}}% / {{item.area}}</strong>
          </b-progress-bar>
        </b-progress>
      </div>

    </div>
  </div>
  
</template>

<script>
import axios from 'axios'
import Spinner from '@/components/Spinner'
import NoFiguresAlert from '@/components/NoFiguresAlert'
import { APP } from '../application-constants'

export default {
  name: 'statistics',
  components: {
    Spinner,
    NoFiguresAlert,
  },
  data() {
    return {
      figures: [],
      getFiguresIsSuccess: false,
      APP,
      fields: [
        {
          key: 'type',
          label: 'Figure type',
          sortable: true
        },
        {
          key: 'area',
          sortable: true
        },
        {
          key: 'percent',
          sortable: true,
        },
      ]
    }
  },

  mounted(){
      axios
      .get(`${APP.endpoints.baseUrl}${APP.endpoints.figures}`)
      .then(response => {
        this.figures = response.data;
        this.getFiguresIsSuccess = true; 
      });
    }, 

  computed: {
    getStatistics() {
      let totalArea = 0; 
      let circlesArea = 0; 
      let squaresArea = 0; 
      let rectanglesArea = 0; 
      let trianglesArea = 0; 

      const Circles = this.figures.filter(figure => figure.type === APP.types.circle); 
      for (let item of Circles){ 
        circlesArea += item.area; 
        totalArea += item.area; 
      } 

      const Squares = this.figures.filter(figure => figure.type === APP.types.square); 
      for (let item of Squares){ 
        squaresArea += item.area; 
        totalArea += item.area; 
      } 

      const Rectangles = this.figures.filter(figure => figure.type === APP.types.rectangle); 
      for (let item of Rectangles){ 
        rectanglesArea += item.area; 
        totalArea += item.area; 
      } 

      const Triangles = this.figures.filter(figure => figure.type === APP.types.triangle); 
      for (let item of Triangles){ 
        trianglesArea += item.area; 
        totalArea += item.area; 
      } 

      const circlePercent = 100*circlesArea/totalArea; 
      const squarePercent = 100*squaresArea/totalArea; 
      const rectanglePercent = 100*rectanglesArea/totalArea; 
      const trianglePercent = 100*trianglesArea/totalArea; 

      const statistics = [
        {
          type: APP.types.circle,
          area: circlesArea,
          percent: Math.round(circlePercent * 1000) / 1000 
        },
        {
          type: APP.types.square,
          area: squaresArea,
          percent: Math.round(squarePercent * 1000) / 1000 
        },
        {
          type: APP.types.rectangle,
          area: rectanglesArea,
          percent:  Math.round(rectanglePercent * 1000) / 1000  
        },
        {
          type: APP.types.triangle,
          area: trianglesArea,
          percent:  Math.round(trianglePercent * 1000) / 1000 
        },
      ]
      return statistics;
    }
  },
  
  methods: {
    checkType(type){
      switch (type) {
        case APP.types.circle:
          return 'warning';

        case APP.types.square:
          return 'danger';

        case APP.types.rectangle:
          return 'primary';

        case APP.types.triangle:
          return 'success'; 

        default:
          return 'secondary';
      }
    }
  },

}
</script>

<style scoped>
  .statistics-section{
    margin-top: 15px;   
  }
  .progress-text{
    font-size: 15px;
  }
</style>
